#ifndef ATTRIBUTETYPE_H
#define ATTRIBUTETYPE_H

enum class AttributeType : unsigned
{
    ENDURANCE,
    SIGHT_RANGE,
    SIGHT_ANGLE,
    HEARING_RANGE,
    SPEED,
    STRENGHT,
    SLEEPING_NECESSITY,
    FOOD_NECESSITY,
    WATER_NECESSITY;

}
#endif // ATTRIBUTETYPE_H
