#ifndef ATTRIBUTETYPE_H
#define ATTRIBUTETYPE_H

enum class AttributeType : unsigned
{
    ENDURANCE = 0,
    SIGHT_RANGE,
    SIGHT_ANGLE,
    HEARING_RANGE,
    SPEED,
    STRENGTH,
    SLEEP_NECESSITY,
    FOOD_NECESSITY,
    WATER_NECESSITY

};

#endif // ATTRIBUTETYPE_H
